Add Name to Contributers
AliceWonderland/hacktoberfest pull request #1257
Opened 2017-10-20 07:58 UTC by Abattisson

Add my name to contributers for the easy win :)

2017-10-20 12:41 UTC, Vic-ST requested changes

2017-10-20 12:41 UTC, StevenCopeland commented on CONTRIBUTORS.md
> -#### Name: [Naman Doshi] (https://github.com/warmachine0609)
Why are you deleting this name?

2017-10-20 12:41 UTC, StevenCopeland commented on CONTRIBUTORS.md
> -#### Name: [Nelson Estevão](https://github.com/nelsonmestevao)
And why are you deleting this name?

2017-11-04 18:32 UTC, Roshanjossey commented
Hi  @Abattisson, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

2020-10-19 15:34 UTC, closed without merging