Hello World in C#
AliceWonderland/hacktoberfest pull request #1317
Opened 2017-10-20 16:17 UTC by gfergo

Hello World -- Your First Program (C# Programming Guide)

2017-10-20 16:17 UTC, gfergo commented
Hello World in C#

2017-10-20 16:19 UTC, Vic-ST reviewed
Please look at the requirments issue(#1292) and change the first comment to look like that.

2017-10-20 16:20 UTC, Vic-ST requested changes
Please change

2017-11-04 18:32 UTC, Roshanjossey commented
Hi  @gfergo, I'm working on a similar project to help beginners to get started with contributing to open source projects.

Do check it out https://github.com/Roshanjossey/first-contributions

2025-06-09 10:16 UTC, closed without merging